book/urls.py
from django.urls import path

from book.views import get_books

app_name = "book"

urlpatterns = [
    path("", get_books, name="get_books"),
]

detail_buku/urls.py
from django.urls import path
from . import views

app_name = 'detail_buku'

urlpatterns = [
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('book/<int:book_id>/like_book/', views.like_book, name='like_book'),
    path('book/<int:book_id>/add_review/', views.add_review, name='add_review'),
    path('book/<int:book_id>/give_rating/', views.give_rating, name='give_rating'),
    path('book/<int:book_id>/give_rating_flutter/', views.give_rating_flutter, name='give_rating_flutter'),
    path('book/<int:book_id>/like_button_flutter/', views.like_button_flutter, name='like_button_flutter'),
    path('book/<int:book_id>/book_detail_json/', views.book_detail_json, name='book_detail_json'),
    path('book/<int:book_id>/add_review_flutter/', views.add_review_flutter, name='add_review_flutter'),
    path('book/json/', views.show_json, name='show_json'),
]

elibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    path('authentication/', include ('authentication.urls')),
    path('my_profile/', include ('my_profile.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('progress_literasi/', include('progress_literasi.urls')),
    path('api/books/', include('book.urls')),
]

home/urls.py
from django.urls import path
from home.views import home
from home.views import show_json, get_book_json, search_book, sort_book, search, sort_az, sort_za

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('json/', show_json, name='show_json'),
    path('get_book/', get_book_json, name='get_book_json'),
    path('search_book/', search_book, name='search_book'),
    path('sort_book/', sort_book, name='sort_book'),
    path('search/<str:query>/', search, name='search'),
    path('json/a-z/', sort_az, name='sort_az'),
    path('json/z-a/', sort_za, name='sort_za'),
]

progress_literasi/urls.py
from django.urls import path
from . import views

app_name = 'progress_literasi'

urlpatterns = [
    path('set-target/', views.set_target, name='set_target'),
    path('progress/', views.progress, name='progress'),
    path('get_text_progress/',views.get_text_progress, name='get_text_progress'),
    path('update_target/', views.update_target, name='update_target'),
    path('reset_target/', views.reset_target, name='reset_target'),
    path('read-book/<int:book_id>/', views.read_book, name='read_book'),
    path('set_target_flutter/', views.set_target_flutter, name='set_target_flutter'),
    path('show_json/', views.show_json, name='show_json'),
    path('read-book-mobile/', views.read_book_mobile),
    path('set_target_flutter/', views.set_target_flutter, name='set_target_flutter'),
    path('show_json/', views.show_json, name='show_json'),
    path('reset_mobile/', views.reset_target_mobile, name='reset_target_mobile'),
    path('get_text_mobile/', views.get_text_mobile, name='get_text_mobile')
]

home/models.py
from django.db import models

class Book (models.Model):

    title = models.CharField(("title"), max_length=255)
    description = models.TextField(("description"))
    authors = models.CharField(("authors"), max_length=255)
    isbn = models.CharField(("isbn"), max_length=150)
    num_pages = models.IntegerField(("number of pages"))
    publisher = models.CharField(("publisher"), max_length=150)
    rating_count = models.IntegerField(("rating count"))
    rating = models.FloatField(("rating"))

home/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.http import JsonResponse
from book.models import Book
from django.db.models import Q

def home(request):
    return render(request, "home.html", {})

def show_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_book_json(request):
    book_item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', book_item))

def search_book(request):
    query = request.GET.get('q', '')
    books = Book.objects.filter(title__icontains=query)
    data = [{'fields': {
        'title': book.title,
        'rating': book.rating,
        'isbn': book.isbn,
        'description': book.description,
        'authors': book.authors,
        'num_pages': book.num_pages,
        'publisher': book.publisher,
        'rating_count': book.rating_count,
    }} for book in books]
    return JsonResponse(data, safe=False)

def sort_book(request):
    sort_order = request.GET.get('sort', 'none')
    if sort_order == 'a_z':
        books = Book.objects.order_by('title')
    elif sort_order == 'z_a':
        books = Book.objects.order_by('-title')
    else:
        books = Book.objects.all()
    data = [{'fields': {
        'title': book.title,
        'rating': book.rating,
        'isbn': book.isbn,
        'description': book.description,
        'authors': book.authors,
        'num_pages': book.num_pages,
        'publisher': book.publisher,
        'rating_count': book.rating_count,
    }} for book in books]
    return JsonResponse(data, safe=False)

# Method untuk flutter
def search(request, query):
    books = Book.objects.filter(
        Q(title__icontains=query) |
        Q(authors__icontains=query) |
        Q(publisher__icontains=query)
    )
    data = [{'fields': {
        'title': book.title,
        'rating': book.rating,
        'isbn': book.isbn,
        'description': book.description,
        'authors': book.authors,
        'num_pages': book.num_pages,
        'publisher': book.publisher,
        'rating_count': book.rating_count,
    }} for book in books]
    return JsonResponse(data, safe=False)

def sort_az(request):
    data = Book.objects.order_by('title')
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def sort_za(request):
    data = Book.objects.order_by('-title')
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

home/templates/home.html
{% extends 'base.html' %}

{% block content %}
<style>
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    body {
        background-color: #f1f1f1;
        padding-top: 60px;
    }

    .card {
        border: none;
    }

    .card-img-top {
        height: 30vh;
        object-fit: cover;
        border-radius: 8px;
    }

    .card-body {
        display: flex;
        flex-direction: column;
    }

    .card-body .btn {
        width: 100%;
        border: none;
        color: #fff;
    }

    .card-text {
        margin-top: auto;
    }
</style>

<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="d-flex mb-3">
                    <div class="input-group">
                        <input type="text" class="form-control" id="search_input" placeholder="Search for books...">
                        <button class="btn btn-outline-secondary" type="button" id="search_button">Search</button>
                    </div>
                    <button class="btn btn-outline-secondary" type="button" id="reset_button"
                        style="display: none; margin-left: 8px;">X</button>
                    <div class="btn-group" id="dropdown_filter">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                            aria-expanded="false" style="margin-left: 8px;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-filter" viewBox="0 0 16 16">
                                <path
                                    d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" id="sort_a_z">A to Z</a></li>
                            <li><a class="dropdown-item" id="sort_z_a">Z to A</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" id="sort_none">None</a></li>
                        </ul>
                    </div>
                </div>
                <h6 class="text-center" id="search_result_text" style="display: none;"></h6>
            </div>
        </div>
        <p id="filter_text" style="display: none;"></p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-4 py-5" id="book_card">

        </div>

    </div>
</body>

<script>
    document.getElementById("search_button").addEventListener("click", function () {
        const query = document.getElementById("search_input").value;
        fetch(`{% url 'home:search_book' %}?q=${query}`).then((res) => res.json()).then((data) => {
            refreshProducts(data);
            document.getElementById("reset_button").style.display = "block";
            document.getElementById("search_result_text").style.display = "block";
            document.getElementById("search_result_text").innerText = `Search result for '${query}'`;

            document.getElementById("dropdown_filter").style.display = "none";
            document.getElementById("filter_text").style.display = "none";
        });
    });

    document.getElementById("reset_button").addEventListener("click", function () {
        getProducts().then(refreshProducts);
        document.getElementById("reset_button").style.display = "none";
        document.getElementById("search_result_text").style.display = "none";
        document.getElementById("search_input").value = "";

        document.getElementById("dropdown_filter").style.display = "block";
    });

    document.getElementById("sort_a_z").addEventListener("click", function () {
        fetch(`{% url 'home:sort_book' %}?sort=a_z`).then((res) => res.json()).then((data) => {
            refreshProducts(data);
            document.getElementById("filter_text").style.display = "block";
            document.getElementById("filter_text").innerText = "Filter: A to Z";
        });
    });

    document.getElementById("sort_z_a").addEventListener("click", function () {
        fetch(`{% url 'home:sort_book' %}?sort=z_a`).then((res) => res.json()).then((data) => {
            refreshProducts(data);
            document.getElementById("filter_text").style.display = "block";
            document.getElementById("filter_text").innerText = "Filter: Z to A";
        });
    });

    document.getElementById("sort_none").addEventListener("click", function () {
        getProducts().then(refreshProducts);
        document.getElementById("filter_text").style.display = "none";
    });

    async function getProducts() {
        return fetch("{% url 'home:get_book_json' %}").then((res) => res.json())
    }

    function refreshProducts(book) {
        document.getElementById("book_card").innerHTML = ""
        let htmlString = ""
        book.forEach((item) => {
            const title = item.fields.title.length >= 50 ? `${item.fields.title.substring(0, 50)}...` : item.fields.title;
            const rating = item.fields.rating_count === 0 ? "No rating" : `Rating: ${item.fields.rating}`;
            console.log(item)
            htmlString += `\n
        <div class="col">
            <div class="card h-100">
                <img class="card-img-top" src="https://covers.openlibrary.org/b/isbn/${item.fields.isbn}-M.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text text-center"><b>${title}</b></p>
                    <p class="card-text text-center">${rating}</p>
                    {% if request.user.is_authenticated %}
                    <button id="read_${item.pk}" class="btn btn-secondary">Read</button>
                    <button style="margin-top: 10px;" id="detail_${item.pk}" class="btn btn-secondary">Detail</button>
                    {% endif %}
                </div>
            </div>
        </div>`
        })

        document.getElementById("book_card").innerHTML = htmlString

        book.forEach((item) => {
            document.getElementById(`read_${item.pk}`).addEventListener("click", function () {
                window.location.href = "{% url 'progress_literasi:read_book' book_id=1 %}".replace(/1/, item.pk.toString());
            });
        });

        // After the HTML string is added to the DOM
        book.forEach((item) => {
            document.getElementById(`detail_${item.pk}`).addEventListener("click", function () {
                window.location.href = "{% url 'detail_buku:book_detail' book_id=1 %}".replace(/1/, item.pk.toString());
            });
        })
    }


    getProducts().then(refreshProducts)
</script>
{% endblock content %}