book/urls.py
from django.urls import path

from book.views import get_books

app_name = "book"

urlpatterns = [
    path("", get_books, name="get_books"),
]

elibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    path('authentication/', include ('authentication.urls')),
    path('my_profile/', include ('my_profile.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('progress_literasi/', include('progress_literasi.urls')),
    path('api/books/', include('book.urls')),
]

my_profile/urls.py
from django.urls import path
from . import views

app_name = 'my_profile'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('get_reading_history_json/', views.get_reading_history_json, name='get_reading_history_json'),
    path('json/', views.get_reading_history, name='json'),
    path('change_password/', views.change_password, name='change_password'), 
    path('change_password_mobile/', views.change_password_mobile, name='set_target'),
]

progress_literasi/urls.py
from django.urls import path
from . import views

app_name = 'progress_literasi'

urlpatterns = [
    path('set-target/', views.set_target, name='set_target'),
    path('progress/', views.progress, name='progress'),
    path('get_text_progress/',views.get_text_progress, name='get_text_progress'),
    path('update_target/', views.update_target, name='update_target'),
    path('reset_target/', views.reset_target, name='reset_target'),
    path('read-book/<int:book_id>/', views.read_book, name='read_book'),
    path('set_target_flutter/', views.set_target_flutter, name='set_target_flutter'),
    path('show_json/', views.show_json, name='show_json'),
    path('read-book-mobile/', views.read_book_mobile),
    path('set_target_flutter/', views.set_target_flutter, name='set_target_flutter'),
    path('show_json/', views.show_json, name='show_json'),
    path('reset_mobile/', views.reset_target_mobile, name='reset_target_mobile'),
    path('get_text_mobile/', views.get_text_mobile, name='get_text_mobile')
]

progress_literasi/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book
    
class ProgressBaca(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    buku = models.ForeignKey(Book, on_delete=models.CASCADE)
    buku_selesai = models.BooleanField(default=False)

class TargetHarian(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    target_buku = models.PositiveIntegerField()

class BukuDibaca(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    buku = models.ForeignKey(Book, on_delete=models.CASCADE)
    counted = models.IntegerField(default=0)

progress_literasi/forms.py
from django.forms import ModelForm
from .models import TargetHarian

class DailyTargetForm(ModelForm):
    class Meta:
        model = TargetHarian
        fields = ['target_buku']

progress_literasi/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from .models import BukuDibaca
from .forms import DailyTargetForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from my_profile.models import ReadingHistory, UserProfile
from book.models import Book
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
from django.core import serializers

@login_required
def set_target(request):
    if request.method == 'POST':
        form = DailyTargetForm(request.POST)
        if form.is_valid():
            target_buku = form.cleaned_data['target_buku']
            user_profile, created = UserProfile.objects.get_or_create(user=request.user)
            user_profile.target_buku = target_buku
            user_profile.save()

            request.session['daily_target'] = target_buku

            return render(request, 'progress.html', {'target_buku': target_buku})
    else:
        form = DailyTargetForm()

    return render(request, 'set_target.html', {'form': form})

@login_required
def progress(request):
    user = request.user
    user_profile = None
    target_buku = None

    try:
        user_profile = UserProfile.objects.get(user=request.user)
        target_buku = user_profile.target_buku
    except ObjectDoesNotExist:
        user_profile = None
        target_buku = 0

    context = {
        'target_buku': target_buku,
    }

    return render(request, 'progress.html', context)

@login_required
def get_text_progress(request):
    user = request.user
    user_profile = None
    target_buku = None
    book_count = 0  

    try:
        user_profile = UserProfile.objects.get(user=user)
        target_buku = user_profile.target_buku if user_profile else None
    except UserProfile.DoesNotExist:
        user_profile = None
        target_buku = 0

    try:
        reading_history = ReadingHistory.objects.get(user=user)
        book_count = reading_history.books.count() 
    except ReadingHistory.DoesNotExist:
        book_count = 0

    selisih = target_buku - book_count if target_buku is not None else None

    if target_buku is not None:
        if target_buku == 0:
            text_progress = "Segera tentukan target jelajahmu!"
        elif book_count >= target_buku:
            text_progress = "Selamat, proses jelajahmu sudah mencapai target!"
        else:
            if selisih is not None:
                if selisih > 0:
                    text_progress = f"Kamu harus membaca {selisih} buku untuk mencapai target jelajahmu!"
                else:
                    text_progress = "Ayo segera mulai petualangan imajinasimu melalui buku!"
            else:
                text_progress = "Segera tentukan target jelajahmu!"
    else:
        text_progress = "Segera tentukan target jelajahmu!"

    return JsonResponse({'text_progress': text_progress})

@login_required
def update_target(request):
    if request.method == 'POST':
        target_buku = request.POST.get('target_buku')
        
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        update_target = request.POST.get('update_target')
        if target_buku is None:
            target_buku = 0
        
        if update_target == '0':
            user_profile.target_buku = 0
        
        user_profile.target_buku = target_buku
        user_profile.save()

        response_data = {'status': 'success', 'message': 'Target harian berhasil diperbarui.'}
        return JsonResponse(response_data)
    
    response_data = {'status': 'error', 'message': 'Permintaan tidak valid.'}
    return JsonResponse(response_data)

@login_required
def reset_target(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        user_profile.target_buku = 0
        user_profile.save()
        return JsonResponse({'success': True, 'message': 'Target harian berhasil direset.'})
    except UserProfile.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Profil pengguna tidak ditemukan.'})
    except Exception as e:
        return JsonResponse({'success': False, 'message': str(e)})

@login_required
def read_book(request, book_id):
    user = get_object_or_404(User, pk=request.user.id)
    book = get_object_or_404(Book, pk=book_id)
    buku_dibaca, created = BukuDibaca.objects.get_or_create(user=user, buku=book)
    if created:
        print(f'BukuDibaca created for user {user} and book {book}')
    else:
        print(f'BukuDibaca already exists for user {user} and book {book}')
    reading_history, created = ReadingHistory.objects.get_or_create(user=user)
    reading_history.books.add(buku_dibaca)
    reading_history.save()

    return redirect('home:home')

@csrf_exempt
def read_book_mobile(request):
    data = json.loads(request.body)
    user_id = data['user_id']
    book_id = data['book_id']
    user = get_object_or_404(User, pk=user_id)
    book = get_object_or_404(Book, pk=book_id)
    buku_dibaca, created = BukuDibaca.objects.get_or_create(user=user, buku=book)
    reading_history, created = ReadingHistory.objects.get_or_create(user=user)

    reading_history.books.add(buku_dibaca)
    reading_history.save()

    return JsonResponse({'message':'Berhasil membaca buku'})

@csrf_exempt
def set_target_flutter(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            target_buku = data.get('Target Buku')  # Adjust the key if needed
            print('data:', data)
            if target_buku is not None:
                existing_target = UserProfile.objects.filter(user=request.user).first()

                if existing_target:
                    # Objek sudah ada, perbarui nilai target_buku
                    existing_target.target_buku = target_buku
                    existing_target.save()
                else:
                    # Objek belum ada, buat objek baru
                    new_target = UserProfile.objects.create(
                        user=request.user,
                        target_buku=target_buku,
                    )
                    new_target.save()

                return JsonResponse({"status": "success"}, status=200)
            else:
                return JsonResponse({"status": "error", "message": "Invalid or missing 'Target Buku' key"}, status=400)

        except json.JSONDecodeError as e:
            return JsonResponse({"status": "error", "message": "Invalid JSON data"}, status=400)

        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)

    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)

@csrf_exempt
def show_json(request):
    data = UserProfile.objects.filter(user=request.user.id)
    serialized_data = serializers.serialize("json", data)
    return HttpResponse(serialized_data, content_type="application/json")

@csrf_exempt
def reset_target_mobile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        user_profile.target_buku = 0
        user_profile.save()
        return JsonResponse({'success': True, 'message': 'Target harian berhasil direset.'})
    except UserProfile.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Profil pengguna tidak ditemukan.'})
    except Exception as e:
        return JsonResponse({'success': False, 'message': str(e)})

@csrf_exempt
def get_text_mobile(request):
    user = request.user
    user_profile = None
    target_buku = None
    book_count = 0  

    try:
        user_profile = UserProfile.objects.get(user=user)
        target_buku = user_profile.target_buku if user_profile else None
    except UserProfile.DoesNotExist:
        user_profile = None
        target_buku = 0

    try:
        reading_history = ReadingHistory.objects.get(user=user)
        book_count = reading_history.books.count() 
    except ReadingHistory.DoesNotExist:
        book_count = 0

    selisih = target_buku - book_count if target_buku is not None else None

    if target_buku is not None:
        if target_buku == 0:
            text_progress = "Segera tentukan target jelajahmu!"
        elif book_count >= target_buku:
            text_progress = "Selamat, proses jelajahmu sudah mencapai target!"
        else:
            if selisih is not None:
                if selisih > 0:
                    text_progress = f"Kamu harus membaca {selisih} buku untuk mencapai target jelajahmu!"
                else:
                    text_progress = "Ayo segera mulai petualangan imajinasimu melalui buku!"
            else:
                text_progress = "Segera tentukan target jelajahmu!"
    else:
        text_progress = "Segera tentukan target jelajahmu!"

    return JsonResponse({'text_progress': text_progress})

progress_literasi/templates/progress.html
{% extends "base.html" %}

{% block content %}
<style>
  h1 {
    font-size: 36px;
    color: #333;
    align-items: center;
    justify-content: center;
    text-align: center;
    margin-top: 80px;
    margin-bottom: 20px;
  }

  h2 {
    font-size: 20px;
    color: #000000;
    margin-left: 15px;
    margin-top: 15px
  }

  ul {
    list-style: none;
  }

  li {
    margin: 5px 0;
    margin-left: 0px;
    font-size: 16px;
    color: #555;
  }

  li.waktu-aktif {
    margin: 5px 0;
    margin-left: 15px;
    font-size: 16px;
    color: #555;
  }

  a.btn-target {
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 15px;
    text-decoration: none;
  }

  p {
    margin-left: 15px;
  }

  strong#progress-text {
    margin-left: 15px;
  }

  .modal {
    display: none;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0, 0, 0, 0.7);
  }

  .modal-content {
    background-color: #fefefe;
    padding: 20px;
    border: 1px solid #888;
    width: 60%;
    box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.2);
    justify-content: center;
    position: relative;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }

  .close {
    color: #aaaaaa;
    font-size: 28px;
    font-weight: bold;
    cursor: pointer;
    position: relative;
    top: 0;
    margin-right: 0;
    margin-bottom: 10px;

  }

  .close:hover {
    color: #000;
  }

  #new-target-input {
    width: 100%;
    padding: 10px;
    margin: 10px 0;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  #save-target-button {
    background-color: #008CBA;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    justify-content: center;
  }

  #save-target-button:hover {
    background-color: #023b64;
  }

  .btn.btn-primary {
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 0px;
    margin-top: 10px;
  }

  .button-container {
    display: flex;
    justify-content: flex-start;
    align-items: center;
  }

  #update-target-button {
    display: inline-block;
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 30px;
    margin-top: 10px;
  }

  #reset-target-button {
    display: inline-block;
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 10px;
    margin-top: 10px;
  }

  button#save-target-button {
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 5px;
    margin-top: 0px;
  }

  #target-input-container {
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 20px;
    margin-top: 0px;
  }

  .centered-container {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .card-row {
    display: flex;
    flex-wrap: wrap;
  }

  .card {
    width: 8rem;
    margin: 10px;
  }

  .card-text {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 100%;
  }

</style>

  <h1>Progress Literasi Anda</h1>
  <br>
  <strong id="progress-text">
  </strong>

  <h2>Target Baca Harian Anda</h2>
  <ul>
    {% if target_buku %}
      <li>Anda ingin membaca <span id="target-buku">{{ target_buku }}</span> buku hari ini.</li>
      <div id="target-message"></div>
    {% else %}
      <li>Anda belum menetapkan target harian.</li>
    {% endif %}
  </ul>
  {% if target_buku %}
    <div class="button-container">
      <button id="update-target-button">Update Target</button>
      <button id="reset-target-button">Reset Target</button>
    </div>
    <div id="target-input-container" class="modal g-0 container-fluid" style="display: none;">
      <div class="modal-content">
        <span class="close" id="close-target-modal">&times;</span>
        <input type="number" id="new-target-input" placeholder="Masukkan target baru">
        <button id="save-target-button">Simpan</button>
      </div>
    </div>
    {% comment %} Add the modal style to your CSS {% endcomment %}
  {% else %}
    <a class="btn-target" href="{% url 'progress_literasi:set_target' %}">Set Target Harian</a>
  {% endif %}

  <h2>Waktu Aktif Pengguna</h1>
  <li class="waktu-aktif">
    <strong>Tanggal:</strong>
    <span id="realtime-date"></span> 
    <strong>Waktu Aktif: {{ elapsed_time }}</strong>
    <span id="realtime-activity"></span> 
  </li>

  <h2>Riwayat Buku</h2>
  <div class="centered-container">
      <div id="book_card" class="card-container">
      </div>
  </div>

<script>
    document.addEventListener("DOMContentLoaded", async function() {
      async function updateProgressText() {
        try {
          const response = await fetch("{% url 'progress_literasi:get_text_progress' %}");
          if (!response.ok) {
            throw new Error("Gagal mengambil data kemajuan.");
          }
          const data = await response.json();
          document.getElementById("progress-text").textContent = data.text_progress;
        } catch (error) {
          console.error(error);
        }
      }

      updateProgressText();

      setInterval(updateProgressText, 1000);
    });
  </script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var updateTargetButton = document.getElementById("update-target-button");
    var resetTargetButton = document.getElementById("reset-target-button");
    var targetInputContainer = document.getElementById("target-input-container");
    var newTargetInput = document.getElementById("new-target-input");
    var saveTargetButton = document.getElementById("save-target-button");
    var targetMessage = document.getElementById("target-message");
    var closeTargetModal = document.getElementById("close-target-modal");

    // Menambahkan event listener ke tombol "Ubah Target"
    updateTargetButton.addEventListener("click", function() {
      updateTargetButton.style.display = "none";
      resetTargetButton.style.display = "none";
      targetInputContainer.style.display = "block";
    });

    // Menambahkan event listener ke tombol "Reset Target"
    resetTargetButton.addEventListener("click", function() {
      // Kirim permintaan AJAX untuk mereset target harian
      fetch("{% url 'progress_literasi:reset_target' %}", {
        method: "POST",
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
        },
      })
        .then(function(response) {
          if (response.ok) {
            return response.json();
          } else {
            throw new Error("Gagal mereset target harian.");
          }
        })
        .then(function(data) {
          // Tampilkan pesan hasil
          targetMessage.textContent = data.message;
          // Perbarui tampilan target harian di halaman
          var targetDisplay = document.querySelector("#target-buku");
          targetDisplay.textContent = "0";
          resetTargetButton.style.display = "none";
          updateTargetButton.style.display = "block";
        })
        .catch(function(error) {
          // Tampilkan pesan kesalahan
          targetMessage.textContent = "Terjadi kesalahan: " + error.message;
        });
        targetInputContainer.style.display = "none";
        updateTargetButton.style.display = "none";
        resetTargetButton.style.display = "none";
    });
    
    // Menambahkan event listener ke tombol "Simpan"
    saveTargetButton.addEventListener("click", function() {
      var newTarget = newTargetInput.value;

      // Kirim permintaan AJAX untuk memperbarui target harian
      var formData = new FormData();
      formData.append("target_buku", newTarget);

      fetch("{% url 'progress_literasi:update_target' %}", {
        method: "POST",
        body: formData,
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
        },
      })
        .then(function(response) {
          if (response.ok) {
            return response.json();
          } else {
            throw new Error("Gagal memperbarui target harian.");
          }
        })
        .then(function(data) {
          // Tampilkan pesan hasil
          targetMessage.textContent = "Target harian berhasil diperbarui!";
          // Perbarui tampilan target harian di halaman
          var targetDisplay = document.querySelector("#target-buku");
          targetDisplay.textContent = newTarget;
          // Sembunyikan kembali input target setelah mengirim permintaan
          targetInputContainer.style.display = "none";
          updateTargetButton.style.display = "block";
          resetTargetButton.style.display = "block";
        })
        .catch(function(error) {
          // Tampilkan pesan kesalahan
          targetMessage.textContent = "Terjadi kesalahan: " + error.message;
        });
    });

    // Menambahkan event listener ke tombol "Close" di modal
    closeTargetModal.addEventListener("click", function() {
      targetInputContainer.style.display = "none";
      updateTargetButton.style.display = "block";
      resetTargetButton.style.display = "block";
    });

    // Fungsi untuk mendapatkan nilai token CSRF
    function getCookie(name) {
      var value = `; ${document.cookie}`;
      var parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop().split(";").shift();
    }
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var dateElement = document.getElementById("realtime-date")
    var activityElement = document.getElementById("realtime-activity");
    var userId = "{{ user.id }}";
    var loginTimestamp = localStorage.getItem("loginTimestamp_" + userId);

    // Fungsi untuk mengupdate waktu aktif sebagai timer
    function updateActivityTimer() {
      var now = new Date();
      var dateString = now.toLocaleDateString();
      var currentTime = Date.now();
      var elapsedTime = Math.floor((currentTime - loginTimestamp) / 1000); // Calculate elapsed time in seconds

      if (!loginTimestamp) {
        // Jika loginTimestamp belum ada, inisialisasi dengan waktu saat ini
        loginTimestamp = currentTime;
        localStorage.setItem("loginTimestamp_" + userId, loginTimestamp);
      }

      if (elapsedTime >= 18000) {
        // Jika lebih dari 5 jam, inisialisasi waktu dari awal
        loginTimestamp = currentTime;
        localStorage.setItem("loginTimestamp", loginTimestamp);
        elapsedTime = 0;
      }

      // Konversi waktu ke format jam:menit:detik
      var hours = Math.floor(elapsedTime / 3600);
      var minutes = Math.floor((elapsedTime % 3600) / 60);
      var seconds = elapsedTime % 60;


      // Format waktu
      var timeString = hours.toString().padStart(2, '0') + ':' +
                      minutes.toString().padStart(2, '0') + ':' +
                      seconds.toString().padStart(2, '0');
      activityElement.textContent = timeString;
      dateElement.textContent = dateString;
    }

    var timerIntervalId = setInterval(updateActivityTimer, 1000);

    function handleLogout() {
      loginTimestamp = null;
      localStorage.removeItem("loginTimestamp_" + userId);

      // Inisialisasi timer dengan waktu saat logout
      updateActivityTimer();

      // Buat interval timer baru untuk pengguna yang login kembali
      timerIntervalId = setInterval(updateActivityTimer, 1000);

    }

    var logoutButton = document.getElementById("btn-logout");
      if (logoutButton) {
        logoutButton.addEventListener("click", function() {
          console.log("logout bang")
          handleLogout();
        });
      }

    updateActivityTimer();

  });
  </script>

<script>
  async function getReadingHistory() {
      return fetch("{% url 'my_profile:get_reading_history_json' %}").then((res) => res.json());
  }

  async function displayReadingHistory() {
      const readingHistory = await getReadingHistory();

      let htmlString = '<div class="card-row">';
      let cardCount = 0;
      readingHistory.forEach((item) => {
          const rating = item.fields.rating_count === 0 ? "No Rating" : item.fields.rating;
          console.log(item)
          htmlString += `\n<div class="card">
              <img class="card-img-top" src="https://covers.openlibrary.org/b/isbn/${item.fields.isbn}-M.jpg" alt="Card image cap" style="width: 100%; height: 200px; object-fit: cover;">
              <div class="card-body">
                  <p class="card-text"><b>${item.fields.title}</b></p>
                  <p class="card-text">${rating}</p>
                  <a href="#" class="btn btn-primary">Detail</a>
              </div>
          </div>`;

          cardCount++;
          if (cardCount === 8) {
              htmlString += '</div><div class="card-row">';
              cardCount = 0;
          }
      });

      htmlString += '</div>';

      const bookCard = document.getElementById("book_card");
      bookCard.innerHTML = htmlString;
  }

  displayReadingHistory();
</script>
  
{% endblock content %}

progress_literasi/templates/set_target.html
{% extends "base.html" %}

{% block content %}

<style>
  h1 {
    text-align: center;
    margin-top: 80px;
    font-size: 36px;
    margin-bottom: 30px;
  }

  form {
    margin-left: 15px;
    margin-bottom: 30px;
  }

  a.btn-kembali {
    margin: 30px auto auto 15px;
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    text-decoration: none;
  }

  button.btn-submit {
    background-color: #0077cc;
    color: #fff;
    padding: 7px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 5px;
  }

</style>

  <h1>Set Target Baca Harian</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.target_buku.label_tag }} {{ form.target_buku }}
    <button class="btn-submit" type="submit">Simpan</button>
  </form>
  <a class="btn-kembali" href="{% url 'progress_literasi:progress' %}">Kembali ke Daftar Buku</a>

  {% endblock %}