book/urls.py
from django.urls import path

from book.views import get_books

app_name = "book"

urlpatterns = [
    path("", get_books, name="get_books"),
]

elibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    path('authentication/', include ('authentication.urls')),
    path('my_profile/', include ('my_profile.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('progress_literasi/', include('progress_literasi.urls')),
    path('api/books/', include('book.urls')),
]

my_profile/urls.py
from django.urls import path
from . import views

app_name = 'my_profile'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('get_reading_history_json/', views.get_reading_history_json, name='get_reading_history_json'),
    path('json/', views.get_reading_history, name='json'),
    path('change_password/', views.change_password, name='change_password'), 
    path('change_password_mobile/', views.change_password_mobile, name='set_target'),
]

my_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from progress_literasi.models import BukuDibaca
# Create your models here.
class ReadingHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(BukuDibaca)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    reading_list = models.ManyToManyField('home.Book', related_name='readers', blank=True)
    history_bacaan = models.ManyToManyField('home.Book', related_name='readers_history', blank=True)
    progress_literasi = models.PositiveIntegerField(default=0)
    target_buku = models.PositiveIntegerField(default=0)
    progress = models.PositiveIntegerField(default=0)

my_profile/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from my_profile.models import UserProfile, ReadingHistory
from progress_literasi.models import BukuDibaca    
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required
def user_profile(request):
    # Mengambil objek UserProfile terkait dengan pengguna saat ini
    user = request.user

    reading_history, created = ReadingHistory.objects.get_or_create(user=user)

    try:
        user_profile = UserProfile.objects.get(user=request.user)
        target_buku = user_profile.target_buku
    except ObjectDoesNotExist:
        user_profile = None
        target_buku = 0

    book_count = reading_history.books.count()
    
    if target_buku > 0:
        if book_count >= target_buku:
            percentage_complete = 100
        else:
            percentage_complete = (book_count * 100) / target_buku
    else:
        percentage_complete = 0

    context = {
        'target_buku': target_buku,
        'reading_history': reading_history,
        'percentage_complete': percentage_complete,
        'book_count': book_count,
    }

    return render(request, 'profile.html', context)

@login_required
def get_reading_history_json(request):
    user = request.user
    try:
        reading_history = ReadingHistory.objects.get(user=user)
        # Ambil semua objek BukuDibaca yang terkait dengan objek ReadingHistory
        buku_dibaca_list = reading_history.books.all()
        # Ambil objek Book yang terkait dengan setiap objek BukuDibaca
        book_list = [buku_dibaca.buku for buku_dibaca in buku_dibaca_list]
        return HttpResponse(serializers.serialize('json', book_list))
    except ReadingHistory.DoesNotExist:
        return JsonResponse([], safe=False)

@login_required
def get_reading_history(request):
    user = request.user
    reading_history = ReadingHistory.objects.get(user=user)
    
    # Ambil semua objek BukuDibaca yang terkait dengan objek ReadingHistory
    buku_dibaca_list = reading_history.books.all()
    
    return HttpResponse(serializers.serialize('json', buku_dibaca_list), content_type="application/json")

@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # Perbarui sesi autentikasi pengguna
            update_session_auth_hash(request, user)
            return JsonResponse({"success": "Password changed successfully"})
        else:
            return JsonResponse({"error": "Invalid password change request"}, status=400)
        
@csrf_exempt
def change_password_mobile(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # Perbarui sesi autentikasi pengguna
            update_session_auth_hash(request, user)
            return JsonResponse({"success": "Password changed successfully", "status": True}, status=200)
        else:
            return JsonResponse({"error": "Invalid password change request", "status": False}, status=400)

my_profile/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .card-row {
        display: flex;
        flex-wrap: wrap;
    }

    .card {
        width: 8rem;
        margin: 10px;
    }

    .card-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        max-width: 100%;
    }
</style>

<body>
    
    <br></br>
    <br></br>
    <h4 class="text-center">Your Progress</h4>
        {% if percentage_complete %}
            <p class="text-center">Progress harian kamu sudah {{ percentage_complete }}% selesai</p>
            <p class="text-center">Kamu sudah membaca {{ book_count }} buku dari total {{ target_buku }} target kamu</p>
            <p class="text-center">Untuk lihat selengkapnya silahkan cek progress literasi di atas</p>
        {% else %}
            <p class="text-center">Kamu belum memiliki progress literasi, tambahkan target harian kamu via progress literasi di atas!</p>
        {% endif %}
    <br>
    <br>
    <h4 class="text-center">Your Reading History</h4>
    <div class="centered-container">
        <div id="book_card">
        </div>
    </div>

    <div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Change Password</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="change_password_form" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="old_password" class="col-form-label">Old Password:</label>
                            <input type="password" class="form-control" id="old_password" name="old_password">
                        </div>
                        <div class="mb-3">
                            <label for="new_password1" class="col-form-label">New Password:</label>
                            <input type="password" class="form-control" id="new_password1" name="new_password1">
                        </div>
                        <div class="mb-3">
                            <label for="new_password2" class="col-form-label">Confirm New Password:</label>
                            <input type="password" class="form-control" id="new_password2" name="new_password2">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_change_password" data-bs-dismiss="modal">Change Password</button>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="text-center">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#changePasswordModal">
            Change Password
        </button>
    </div>
    
</body>

<script>
    // Your JavaScript code here
    async function getReadingHistory() {
        return fetch("{% url 'my_profile:get_reading_history_json' %}").then((res) => res.json());
    }

    async function displayReadingHistory() {
        const readingHistory = await getReadingHistory();

        let htmlString = '<div class="card-row">';
        let cardCount = 0;
        readingHistory.forEach((item) => {
            const rating = item.fields.rating_count === 0 ? "No Rating" : item.fields.rating;
            console.log(item)
            htmlString += `\n<div class="card"">
                <img class="card-img-top" src="https://covers.openlibrary.org/b/isbn/${item.fields.isbn}-M.jpg" alt="Card image cap" style="width: 100%; height: 200px; object-fit: cover;">
                <div class="card-body">
                    <p class="card-text"><b>${item.fields.title}</b></p>
                    <p class="card-text">${rating}</p>
                    <a href="#" class="btn btn-primary">Detail</a>
                </div>
            </div>`;

            cardCount++;
            if (cardCount === 7) {
                htmlString += '</div><div class="card-row">';
                cardCount = 0;
            }
        });

        htmlString += '</div>';

        document.getElementById("book_card").innerHTML = htmlString;
    }

    displayReadingHistory();

    function changePassword() {
        fetch("{% url 'my_profile:change_password' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#change_password_form'))
        })
        .then((response) => {
            if (response.status === 200) {
                // Jika perubahan password berhasil, tampilkan pesan sukses.
                alert("Password changed successfully");
            } else {
                // Jika terjadi kesalahan, tampilkan pesan error.
                alert("Error: Password change failed");
            }
        })
        .catch((error) => {
            console.error("Error:", error);
        });

        document.getElementById("change_password_form").reset();
    }

    document.getElementById("button_change_password").onclick = changePassword;
</script>
{% endblock content %}