admin_app/urls.py
from django.urls import path
from admin_app.views import admin_app, show_user_json, get_user_json, get_log_json, add_book, edit_book, delete_book, delete_user, get_username_json, get_book_json, delete_cookie, update_cookie, create_book_flutter

app_name = 'admin_app'

urlpatterns = [
    path('get_book/<str:q>/', get_book_json, name='get_book_json'),
    path('user_json/', show_user_json, name='show_user_json'),
    path('get_user/', get_user_json, name='get_user_json'),
    path('get_username/<int:id>/', get_username_json, name='get_username_json'),
    path('get_log/<int:id>/', get_log_json, name='get_log_json'),
    path('admin_app/', admin_app, name='admin_app'),
    path('add_book/', add_book, name='add_book'),
    path('edit_book/<int:id>/', edit_book, name='edit_book'),
    path('delete_book/<int:id>/', delete_book, name='delete_book'),
    path('delete_user/<int:id>/', delete_user, name='delete_user'),
    path('delete_cookie/', delete_cookie, name='delete_cookie'),
    path('update_cookie/', update_cookie, name='update_cookie'),
    path('create_flutter/', create_book_flutter, name='create_book_flutter'),
]

authentication/urls.py
from django.urls import path
from authentication.views import register, login_user, logout_user, login_mobile, logout_mobile, register_mobile

app_name = 'authentication'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('mobile-login/', login_mobile, name='login_flutter'),
    path('mobile-logout/', logout_mobile, name='logout_flutter'),
    path('mobile-register/', register_mobile, name='register_flutter')
]

book/urls.py
from django.urls import path

from book.views import get_books

app_name = "book"

urlpatterns = [
    path("", get_books, name="get_books"),
]

elibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    path('authentication/', include ('authentication.urls')),
    path('my_profile/', include ('my_profile.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('progress_literasi/', include('progress_literasi.urls')),
    path('api/books/', include('book.urls')),
]

home/urls.py
from django.urls import path
from home.views import home
from home.views import show_json, get_book_json, search_book, sort_book, search, sort_az, sort_za

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('json/', show_json, name='show_json'),
    path('get_book/', get_book_json, name='get_book_json'),
    path('search_book/', search_book, name='search_book'),
    path('sort_book/', sort_book, name='sort_book'),
    path('search/<str:query>/', search, name='search'),
    path('json/a-z/', sort_az, name='sort_az'),
    path('json/z-a/', sort_za, name='sort_za'),
]

my_profile/urls.py
from django.urls import path
from . import views

app_name = 'my_profile'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('get_reading_history_json/', views.get_reading_history_json, name='get_reading_history_json'),
    path('json/', views.get_reading_history, name='json'),
    path('change_password/', views.change_password, name='change_password'), 
    path('change_password_mobile/', views.change_password_mobile, name='set_target'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        .navbar {
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        }

        #btn-login {
            margin-right: 10px;
        }

        .navbar-container {
            padding-left: 80px;
            padding-right: 80px;
        }

        .bi {
            margin: 4px;
        }
    </style>
</head>

<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container-fluid navbar-container">
        <a class="navbar-brand">
            <img class="logo" src="{% static 'logo.png' %}" width="30" height="30" alt="">
            <b>E-Library</b>
        </a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">My Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'progress_literasi:progress' %}">Progres Literasi</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        {% url 'my_profile:user_profile' as profile_url %}
        <span class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Hi, {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ profile_url }}"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                        height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                    </svg>Profile</a>
                {% if request.user.is_staff %}
                <a class="dropdown-item" href="{% url 'admin_app:admin_app' %}"><svg xmlns="http://www.w3.org/2000/svg"
                        width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                        <path
                            d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z" />
                    </svg>Administration</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'authentication:logout' %}"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
                        <path fill-rule="evenodd"
                            d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
                    </svg>Log out</a>
            </div>
        </span>

        {% else %}
        <a class="nav-link" href="{% url 'authentication:login' %}">Log in<svg xmlns="http://www.w3.org/2000/svg"
                width="18" height="18" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                <path fill-rule="evenodd"
                    d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
            </svg>
        </a>
        {% endif %}

    </div>
</nav>

{% block content %}
{% endblock content %}

</html>